// Liste des catégories d"associations loi 1901
const categories = [
  {
    value: 'socialCulturalAction',
    label: 'Action socio-culturelle',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'politicalActivities',
    label: 'Activités politiques',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'religiousSpiritualPhilo',
    label: 'Activités religieuses, spirituelles ou philosophiques',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'employmentSolidarity',
    label: "Aide à l'emploi, développement local, solidarité",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'friendshipsSelfhelp',
    label: "Amicales, groupements affinitaires et d'entraide",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'army',
    label: 'Armée',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'charityHumanitarian',
    label: 'Associations carritatives et humanitaires',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'huntingFishing',
    label: 'Chasse pêche',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'leisureRelationships',
    label: 'Clubs de loisirs, relations',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'thinkTank',
    label: 'Clubs, cercle de réflexion',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'economic',
    label: "Conduite d'activités économiques",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'cultureArts',
    label: 'Culture, activités artistiques, culturelles',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'fundamentalRights',
    label: 'Défense des droits fondamentaux',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'others',
    label: 'Domaines divers',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'educationTraining',
    label: 'Education Formation',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'environmentLiving',
    label: 'Environnement, Cadre de vie',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'informationCommunication',
    label: 'Information et communication',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'socialIntervention',
    label: 'Intervention sociale',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'justice',
    label: 'Justice',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'accomodation',
    label: 'Logement',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'heritagePreservation',
    label: 'Préservation du patrimoine',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'research',
    label: 'Recherche',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'promotionEconomicInterests',
    label: "Défense d'intérêts économiques",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'health',
    label: 'Santé',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'security',
    label: 'Sécurité, Protection civile',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'medicalSocialServicies',
    label: 'Services et établissements médico-sociaux',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'familySeniorServicies',
    label: 'Services aux personnes âgées',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'sports',
    label: 'Sports, activités de plein air',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'tourism',
    label: 'Tourisme',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = categories;
