// Liste des catégories d"associations loi 1901
const categories = [
  {
    label: "socialCulturalAction",
    value: "Action socio-culturelle",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "politicalActivities",
    value: "Activités politiques",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "religiousSpiritualPhilo",
    value: "Activités religieuses, spirituelles ou philosophiques",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "employmentSolidarity",
    value: "Aide à l'emploi, développement local, promotion de solidarité",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "friendshipsSelfhelp",
    value: "Amicales, groupements affinitaires, groupements d'entraide",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "army",
    value: "Armée",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "charityHumanitarian",
    value: "Associations carritatives et humanitaires",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "huntingFishing",
    value: "Chasse pêche",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "leisureRelationships",
    value: "Clubs de loisirs, relations",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "thinkTank",
    value: "Clubs, cercle de réflexion",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "economic",
    value: "Conduite d'activités économiques",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "cultureArts",
    value: "Culture, pratiques d'activités artistiques, culturelles",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "fundamentalRights",
    value: "Défense des droits fondamentaux",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "others",
    value: "Domaines divers",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "educationTraining",
    value: "Education Formation",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "environmentLiving",
    value: "Environnement, Cadre de vie",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "informationCommunication",
    value: "Information et communication",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "socialIntervention",
    value: "Intervention sociale",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "justice",
    value: "Justice",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "accomodation",
    value: "Logement",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "heritagePreservation",
    value: "Préservation du patrimoine",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "research",
    value: "Recherche",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "promotionEconomicInterests",
    value: "Représentation, promotion, et défense d'intérêts économiques",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "health",
    value: "Santé",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "security",
    value: "Sécurité, Protection civile",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "medicalSocialServicies",
    value: "Services et établissements médico-sociaux",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "familySeniorServicies",
    value: "Services familiaux et services aux personnes âgées",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "sports",
    value: "Sports, activités de plein air",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "tourism",
    value: "Tourisme",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = categories;