const skills = [
  {
    label: "html",
    value: 'HTML',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "css",
    value: 'CSS',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "php",
    value: 'PHP',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "laravel",
    value: 'Laravel',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "symfony",
    value: 'Symfony',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "js",
    value: 'JavaScript',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "react",
    value: 'React',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "angular",
    value: 'Angular',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "vue",
    value: 'Vue',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "node",
    value: 'Node',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "express",
    value: 'Express',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "mysql",
    value: 'MySQL',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "mongodb",
    value: 'MongoDB',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "sequelize",
    value: 'Sequelize',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "mongoose",
    value: 'Mongoose',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "bootstrap",
    value: 'Bootstrap',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "jquery",
    value: 'jQuery',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "git",
    value: 'Git',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "github",
    value: 'GitHub',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "wordpress",
    value: 'WordPress',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "prestashop",
    value: 'PrestaShop',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "java",
    value: 'Java',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "python",
    value: 'Python',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "c",
    value: 'C',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "cplusplus",
    value: 'C++',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "csharp",
    value: 'C#',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    label: "swift",
    value: 'Swift',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = skills;