const skills = [
  {
    value: 'html',
    label: 'HTML',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'css',
    label: 'CSS',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'php',
    label: 'PHP',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'laravel',
    label: 'Laravel',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'symfony',
    label: 'Symfony',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'js',
    label: 'JavaScript',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'react',
    label: 'React',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'angular',
    label: 'Angular',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'vue',
    label: 'Vue',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'node',
    label: 'Node',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'express',
    label: 'Express',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'mysql',
    label: 'MySQL',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'mongodb',
    label: 'MongoDB',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'sequelize',
    label: 'Sequelize',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'mongoose',
    label: 'Mongoose',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'bootstrap',
    label: 'Bootstrap',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'jquery',
    label: 'jQuery',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'git',
    label: 'Git',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'github',
    label: 'GitHub',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'wordpress',
    label: 'WordPress',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'prestashop',
    label: 'PrestaShop',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'java',
    label: 'Java',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'python',
    label: 'Python',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'c',
    label: 'C',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'cplusplus',
    label: 'C++',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'csharp',
    label: 'C#',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    value: 'swift',
    label: 'Swift',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = skills;
